[project]
name = "zk-bulletproofs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "libnum>=1.7.1",
    "py-ecc>=8.0.0",
]

[dependency-groups]
dev = [
    "pyright>=1.1.409",
    "ruff>=0.15.12",
]

[tool.ruff]
line-length = 88
select = ["E", "F", "I"]
